src/OID.Web/Controllers/DealController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OID.DataProvider.Interfaces;
using OID.DataProvider.Models;
using OID.DataProvider.Models.Deal;
using OID.DataProvider.Models.Deal.In;
using OID.DataProvider.Models.User;
using OID.Web.Core;
using OID.Web.Models;
using OID.Web.Models.Deal;
using OID.Web.Models.Partials;
using OID.Web.Models.User;


namespace OID.Web.Controllers
{
    [Authorize("HasSessionID")]
    public class DealController : OIDController
    {
        private readonly IDealProvider _dealProvider;
        private readonly IMapper _mapper;
        private readonly IDealObjectProvider _dealObjectProvider;
        private readonly IUserProvider _userProvider;
        private readonly IRegionProvider _regionProvider;

        public DealController(IDealProvider dealProvider, IMapper mapper, IDealObjectProvider dealObjectProvider, IUserProvider userProvider, IRegionProvider regionProvider)
        {
            _dealProvider = dealProvider;
            _mapper = mapper;
            _dealObjectProvider = dealObjectProvider;
            _userProvider = userProvider;
            _regionProvider = regionProvider;
        }

        public async Task<IActionResult> Index()
        {
            var deals = await _dealProvider.GetDeals();
            if (deals.ResultMessage.MessageType != MessageType.Error)
            {
                var model = _mapper.Map<List<ItemDealViewModel>>(deals.Model);
                return View(model);
            }
            else
            {
                ShowError(deals.ResultMessage.Message);
            }

            return RedirectToIndex();
        }

        public async Task<IActionResult> UpdateBuy(int dealId)
        {
            var dealModifyModel = await CreateUpdateDealModel(dealId);

            var model = new UpdateBuyDealViewModel
            {
                DealId = dealId,
                DealModel = dealModifyModel
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBuy(int dealId, DealModifyModel modfyModel)
        {
            var currentDeliveryObjectsTask = _dealObjectProvider.GetDealObjects(dealId);

            var currentDeliveryObjects = (await currentDeliveryObjectsTask).Model;

            var objectsToDelete = currentDeliveryObjects
                .Where(c => modfyModel.SelectedDealObjects.All(s => s.ObjectId != c.ObjectId))
                .Select(o => o.DealObjectId)
                .ToList();

            var objectsToAdd = modfyModel.SelectedDealObjects
                .Where(s => currentDeliveryObjects.All(c => c.ObjectId != s.ObjectId))
                .Select(o => o.ObjectId)
                .ToList();

            var updateModel = new DealUpdateModel(dealId, objectsToDelete, objectsToAdd, modfyModel.Price, modfyModel.Comment, null, modfyModel.DeleveryTypeId,
                modfyModel.Size, modfyModel.Weight, modfyModel.AddressModel.City.CityCode, modfyModel.AddressModel.Locality.LocalityCode,
                modfyModel.AddressModel.RegionCode, modfyModel.AddressModel.Address, (DeleveryLocationType) modfyModel.AddressModel.DeliveryLocationType);

            await _dealProvider.UpdateDeal(updateModel, DealType.Buy);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> CreateBuy()
        {
            var model = await CreateDealModifyModel(DealType.Buy);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateBuy(DealModifyModel model)
        {
            var objectIdsToAdd = model.SelectedDealObjects
                .Select(o => o.ObjectId)
                .ToList();

            var createModel = new DealCreateModel(model.Price, model.Comment, null, model.DeleveryTypeId, model.Size,
                model.Weight, model.AddressModel.City.CityCode, model.AddressModel.Locality.LocalityCode, model.AddressModel.RegionCode,
                model.AddressModel.Address, (DeleveryLocationType) model.AddressModel.DeliveryLocationType, objectIdsToAdd);

            await _dealProvider.CreateDeal(createModel, DealType.Buy);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UpdateSell(int dealId)
        {
            var sellModifyModel = await CreateUpdateDealModel(dealId);

            var model = new UpdateSellDealViewModel
            {
                DealId = dealId,
                SellDealModel = sellModifyModel
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSell(int dealId, SellDealModifyViewModel modfyModel)
        {
            var currentDeliveryObjectsTask = _dealObjectProvider.GetDealObjects(dealId);
            var createUserAccountTask = Task.FromResult(new DataProviderModel<CreateUserAccountModel>(new ResultMessage(0, MessageType.Information, "")));
            if (modfyModel.AccountAction == AccountAction.New)
            {
                createUserAccountTask = _userProvider.CreateUserAccount(modfyModel.PaymentNumber.Value, modfyModel.PaymentType);
            }

            await Task.WhenAll(currentDeliveryObjectsTask, createUserAccountTask);

            var currentDeliveryObjects = currentDeliveryObjectsTask.Result.Model;
            var createUserAccount = createUserAccountTask.Result.Model;

            var objectsToDelete = currentDeliveryObjects
                .Where(c => modfyModel.SelectedDealObjects.All(s => s.ObjectId != c.ObjectId))
                .Select(o => o.DealObjectId)
                .ToList();

            var objectsToAdd = modfyModel.SelectedDealObjects
                .Where(s => currentDeliveryObjects.All(c => c.ObjectId != s.ObjectId))
                .Select(o => o.ObjectId)
                .ToList();

            var accountId = modfyModel.AccountAction == AccountAction.Existed ? modfyModel.UserAccountId.Value : createUserAccount.AccountId;

            var updateModel = new DealUpdateModel(dealId, objectsToDelete, objectsToAdd, modfyModel.Price, modfyModel.Comment, accountId, modfyModel.DeleveryTypeId,
                modfyModel.Size, modfyModel.Weight, modfyModel.AddressModel.City.CityCode, modfyModel.AddressModel.Locality.LocalityCode,
                modfyModel.AddressModel.RegionCode, modfyModel.AddressModel.Address, (DeleveryLocationType) modfyModel.AddressModel.DeliveryLocationType);

            await _dealProvider.UpdateDeal(updateModel, DealType.Sell);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> CreateSell()
        {
            var model = await CreateSellModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateSell(SellDealModifyViewModel model)
        {
            var createUserAccountTask = Task.FromResult(new DataProviderModel<CreateUserAccountModel>(new ResultMessage(0, MessageType.Information, "")));
            if (model.AccountAction == AccountAction.New)
            {
                createUserAccountTask = _userProvider.CreateUserAccount(model.PaymentNumber.Value, model.PaymentType);
            }

            var createUserAccount = (await createUserAccountTask).Model;

            var accountId = model.AccountAction == AccountAction.Existed ? model.UserAccountId.Value : createUserAccount.AccountId;
            var objectIdsToAdd = model.SelectedDealObjects
                .Select(o => o.ObjectId)
                .ToList();

            var createModel = new DealCreateModel(model.Price, model.Comment, accountId, model.DeleveryTypeId, model.Size,
                model.Weight, model.AddressModel.City.CityCode, model.AddressModel.Locality.LocalityCode, model.AddressModel.RegionCode,
                model.AddressModel.Address, (DeleveryLocationType) model.AddressModel.DeliveryLocationType, objectIdsToAdd);

            await _dealProvider.CreateDeal(createModel, DealType.Sell);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ViewDeal(int dealId)
        {
            var dealTask = _dealProvider.GetDeal(dealId);
            var deliveryTask = _dealProvider.GetDealDelevery(dealId);
            var objectsTask = _dealObjectProvider.GetDealObjects(dealId);
            var paymentsTask = _dealProvider.GetDealPayments(dealId);
            var cheksTask = _dealObjectProvider.GetChecksFromDeal(dealId);

            await Task.WhenAll(dealTask, deliveryTask, objectsTask, paymentsTask, cheksTask);

            var deal = dealTask.Result.Model;
            var delivery = deliveryTask.Result.Model;
            var objects = objectsTask.Result.Model;
            var checks = cheksTask.Result.Model;

            var objectsWithChecks = new List<ViewDealModel.DealObject>();
            foreach (var dealObject in objects)
            {
                var dealChecks = new List<ViewDealModel.DealObject.ObjectCheck>();
                foreach (var check in checks.Where(ch => ch.ObjectId == dealObject.ObjectId))
                {
                    dealChecks.Add(new ViewDealModel.DealObject.ObjectCheck
                    {
                        Description = check.Task
                    });
                }

                objectsWithChecks.Add(new ViewDealModel.DealObject
                {
                    ObjectId = dealObject.ObjectId,
                    CheckListId = dealObject.CheckListId,
                    ObjectName = dealObject.ObjectName,
                    AcceptedByMe = dealObject.IsApprovedByMe,
                    AcceptedByPartner = dealObject.IsApprovedByPartner,
                    ObjectChecks = dealChecks,
                    DealObjectId = dealObject.DealObjectId

src/OID.Web/Views/Shared/_Address.cshtml
@using System.Threading.Tasks
@using OID.Web.Models.Partials
@using OID.Web.Models.User
@model OID.Web.Models.Partials.AddressViewModel

<div class="form-group">
    <div class="col-md-10">
        <div class="row">
            <div class="col-md-12">
                <label asp-for="DeliveryLocationType" style="margin-right: 10px" class="control-label"></label>
                <input name="@(Model.ModelPrefix).DeliveryLocationType" asp-for="DeliveryLocationType" type="radio" data-radio-identifier="deleveryType" value="@AddressType.City" @(Model.DeliveryLocationType= =AddressType.City?"checked":"") /> Город
                <input name="@(Model.ModelPrefix).DeliveryLocationType" asp-for="DeliveryLocationType" type="radio" data-radio-identifier="deleveryType" value="@AddressType.Locality" @(Model.DeliveryLocationType= =AddressType.Locality?"checked":"") /> Населенный пункт
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="col-md-10">
        <div class="row">
            <label asp-for="RegionCode" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select name="@(Model.ModelPrefix).RegionCode" asp-for="RegionCode" id="regionList" class="form-control" asp-items="@Model.RegionList"></select>
            </div>
        </div>
    </div>
</div>
<div data-region="@AddressType.City" data-radio-identifier="deleveryType" style="display: @(Model.DeliveryLocationType==AddressType.City?"block":"none")">
    <div class="form-group">
        <div class="col-md-10">
            <div class="row">
                <label asp-for="City.CityCode" class="control-label col-md-2"></label>
                <div class="col-md-10">
                    <select name="@(Model.ModelPrefix).City.CityCode" id="cityList" asp-for="City.CityCode" class="form-control" asp-items="@Model.City.CityList"></select>
                </div>
            </div>
        </div>
    </div>
</div>

<div data-region="@AddressType.Locality" data-radio-identifier="deleveryType" style="display: @(Model.DeliveryLocationType==AddressType.Locality?"block":"none")">
    <div class="form-group">
        <div class="col-md-10">
            <div class="row">
                <label asp-for="Locality.LocalityCode" class="control-label col-md-2"></label>
                <div class="col-md-10">
                    <select name="@(Model.ModelPrefix).Locality.LocalityCode" id="localityList" asp-for="Locality.LocalityCode" class="form-control" asp-items="@Model.Locality.LocalityList"></select>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <div class="row">
                <label asp-for="Locality.LocationCode" class="control-label col-md-2"></label>
                <div class="col-md-10">
                    <select name="@(Model.ModelPrefix).Locality.LocationCode" id="locationList" asp-for="Locality.LocationCode" class="form-control" asp-items="@Model.Locality.LocationList"></select>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="col-md- col-md-10">
        <div class="row">
            <label asp-for="Address" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <textarea name="@(Model.ModelPrefix).Address" asp-for="Address" class="form-control"></textarea>
            </div>
        </div>
    </div>
</div>

src/OID.Web/Views/Shared/_AddressWithoutBootstrap.cshtml
@using System.Threading.Tasks
@using OID.Web.Models.User
@model OID.Web.Models.Partials.AddressViewModel

<div class="form-group">
    <div>
        <div>
            <div>
                <div>
                    <label asp-for="DeliveryLocationType" style="margin-right: 10px" class="control-label"></label>
                </div>
                <input name="@(Model.ModelPrefix).DeliveryLocationType" asp-for="DeliveryLocationType" type="radio" data-radio-identifier="deleveryType" value="@AddressType.City" @(Model.DeliveryLocationType = = AddressType.City ? "checked" : "")/> Город
                <input name="@(Model.ModelPrefix).DeliveryLocationType" asp-for="DeliveryLocationType" type="radio" data-radio-identifier="deleveryType" value="@AddressType.Locality" @(Model.DeliveryLocationType = = AddressType.Locality ? "checked" : "")/> Населенный пункт
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <div>
        <div>
            <label asp-for="RegionCode" class="control-label"></label>
            <select name="@(Model.ModelPrefix).RegionCode" asp-for="RegionCode" id="regionList" class="form-control" asp-items="@Model.RegionList"></select>
        </div>
    </div>
</div>
<div data-region="@AddressType.City" data-radio-identifier="deleveryType" style="display: @(Model.DeliveryLocationType==AddressType.City?"block":"none")">
    <div class="form-group">
        <div>
            <div>
                <label asp-for="City.CityCode" class="control-label"></label>
                <div>
                    <select name="@(Model.ModelPrefix).City.CityCode" id="cityList" asp-for="City.CityCode" class="form-control" asp-items="@Model.City.CityList"></select>
                </div>
            </div>
        </div>
    </div>
</div>

<div data-region="@AddressType.Locality" data-radio-identifier="deleveryType" style="display: @(Model.DeliveryLocationType==AddressType.Locality?"block":"none")">
    <div class="form-group">
        <div>
            <div>
                <label asp-for="Locality.LocalityCode" class="control-label"></label>
                <div>
                    <select name="@(Model.ModelPrefix).Locality.LocalityCode" id="localityList" asp-for="Locality.LocalityCode" class="form-control" asp-items="@Model.Locality.LocalityList"></select>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div>
            <div>
                <label asp-for="Locality.LocationCode" class="control-label"></label>
                <div>
                    <select name="@(Model.ModelPrefix).Locality.LocationCode" id="locationList" asp-for="Locality.LocationCode" class="form-control" asp-items="@Model.Locality.LocationList"></select>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <div>
        <div>
            <label asp-for="Address" class="control-label"></label>
            <div>
                <textarea name="@(Model.ModelPrefix).Address" asp-for="Address" class="form-control"></textarea>
            </div>
        </div>
    </div>
</div>

src/OID.Web/Views/Shared/_AlertMessage.cshtml
@using Microsoft.AspNetCore.Html
@using Newtonsoft.Json
@using OID.Web.Core.AlertMessage
@using Constants = OID.Web.Core.Constants

@functions
{
    HtmlString GetClassForMessage(MessageType messageType)
    {
        switch (messageType)
        {
            case MessageType.Error:
                return new HtmlString("danger");
            case MessageType.Warning:
                return new HtmlString("warning");
            case MessageType.Success:
                return new HtmlString("success");
            case MessageType.Info:
                return new HtmlString("info");
            default:
                throw new ArgumentOutOfRangeException(nameof(messageType), messageType, null);
        }
    }
}

@if (TempData[Constants.ALERT_MESSAGE] != null)
{
    var message = JsonConvert.DeserializeObject<Message>(TempData[Constants.ALERT_MESSAGE].ToString());
    <div class="alert alert-@GetClassForMessage(message.MessageType) alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @message.Text
    </div>
}

src/OID.Web/Views/Shared/_ConfirmAlert.cshtml
<div class="modal fade" id="confirmAlert">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Удаление объекта</h4>
            </div>
            <div class="modal-body">
                <p>Вы действительно хотите удалить объект?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
                <button type="button" id="btnConfirm" class="btn btn-primary" data-dismiss="modal">Да</button>
            </div>
        </div>
    </div>
</div>

src/OID.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Оплата и доставка</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Оплата и доставка</a>
            </div>
            <div class="navbar-collapse collapse">
                @await Html.PartialAsync("_MenuPartial")
            </div>
        </div>
    </div>
    <div class="container body-content" style="padding-top: 10px">
        @await Html.PartialAsync("_AlertMessage")
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Оплата и доставка</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/delevery.js"></script>
        <script src="~/lib/angular/angular.js"></script>
        <script src="~/js/regions.js"></script>
        <script src="~/js/dealObject.js"></script>
        <script src="js/alert.js"></script>
        <script src="~/js/dealObjectsList.js"></script>
        <script src="~/js/dealList.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"
                asp-fallback-src="~/lib/angular/angular.min.js"
                asp-fallback-test="window.angular">
        </script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/OID.Web/Views/Shared/_MenuPartial.cshtml
@using System.Threading.Tasks
@using OID.Core

@inject IUserManager UserManager

@{
    var user = UserManager.GetUser();
}

@if (user != null)
{
    <ul class="nav navbar-nav">
        <li><a asp-controller="Deal" asp-action="Index">Сделки</a></li>
        <li><a asp-area="" asp-controller="Object" asp-action="Index">Объекты</a></li>
        <li><a asp-area="" asp-controller="User" asp-action="Manage">Мои контакты</a></li>
    </ul>
    <form asp-area="" asp-controller="User" asp-action="LogOff" method="post" id="logoutForm" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a asp-area="" asp-controller="User" asp-action="Manage" title="Manage">Привет @user.Login!</a>
            </li>
            <li>
                <button type="submit" class="btn btn-link navbar-btn navbar-link">Выйти</button>
            </li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a asp-area="" asp-controller="User" asp-action="Register">Регистрация</a></li>
        <li><a asp-area="" asp-controller="User" asp-action="Login">Войти</a></li>
    </ul>
}