src/OID.Web/Models/Deal/AccountAction.cs
using System.ComponentModel.DataAnnotations;

namespace OID.Web.Models.Deal
{
    public enum AccountAction
    {
        [Display(Name = "Существующий")]
        Existed = 1,

        [Display(Name = "Новый")]
        New = 2
    }
}

src/OID.Web/Models/Deal/DealModifyModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using OID.DataProvider.Models.Deal;
using OID.DataProvider.Models.User;
using OID.Web.Models.Partials;

namespace OID.Web.Models.Deal
{
    public class DealModifyModel
    {
        public DealModifyModel()
        {
            SelectedDealObjects = new List<SelectedDealObject>();
        }

        public SelectList FreeDealObjects { get; set; }

        public IList<SelectedDealObject> SelectedDealObjects { get; set; }

        [Display(Name = "Цена")]
        public double Price { get; set; }

        [Display(Name = "Комментарий")]
        public string Comment { get; set; }

        public SelectList DeleveryTypes { get; set; }

        [Display(Name = "Тип доставки")]
        public int DeleveryTypeId { get; set; }

        [Display(Name = "Вес")]
        public int Weight { get; set; }

        [Display(Name = "Размеры")]
        public Size Size { get; set; }

        public AddressViewModel AddressModel { get; set; }

        [Display(Name = "Тип счета")]
        public PaymentType PaymentType { get; set; }

        [Display(Name = "Номер счета")]
        public int? PaymentNumber { get; set; }

        public AccountAction AccountAction { get; set; } = AccountAction.New;
    }
}

src/OID.Web/Models/Deal/DealObject.cs
namespace OID.Web.Models.Deal
{
    public class DealObject
    {
        public string Name { get; set; }

        public string Description { get; set; }

        public int ObjectId { get; set; }
    }
}

src/OID.Web/Models/Deal/DealViewModel.cs
using System;
using OID.DataProvider.Models.Deal;

namespace OID.Web.Models.Deal
{
    public class DealViewModel
    {
        public string Objects { get; set; }

        public double Price { get; set; }

        public string Comment { get; set; }

        public int DealId { get; set; }

        public int Pin { get; set; }

        public DealType DealType { get; set; }

        public bool Blocked { get; set; }

        public bool IsMyDeal { get; set; }

        public DateTime CreateDate { get; set; }
    }
}

src/OID.Web/Models/Deal/ItemDealViewModel.cs
using System;
using OID.DataProvider.Models.Deal;

namespace OID.Web.Models.Deal
{
    public class ItemDealViewModel
    {
        public string Objects { get; set; }

        public double Price { get; set; }

        public string Comment { get; set; }

        public int DealId { get; set; }

        public int Pin { get; set; }

        public DealType DealType { get; set; }

        public bool Blocked { get; set; }

        public bool IsMyDeal { get; set; }

        public DateTime CreateDate { get; set; }
    }
}

src/OID.Web/Models/Deal/SelectedDealObject.cs
namespace OID.Web.Models.Deal
{
    public class SelectedDealObject
    {
        public int ObjectId { get; set; }

        public string Name { get; set; }
    }
}

src/OID.Web/Models/Deal/SellDealModifyViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace OID.Web.Models.Deal
{
    public class SellDealModifyViewModel: DealModifyModel
    {
        public SelectList UserAccounts { get; set; }

        [Display(Name = "Номер счета")]
        public int? UserAccountId { get; set; }
    }
}

src/OID.Web/Models/Deal/UpdateBuyDealViewModel.cs
namespace OID.Web.Models.Deal
{
    public class UpdateBuyDealViewModel
    {
        public int DealId { get; set; }

        public DealModifyModel DealModel { get; set; }
    }
}

src/OID.Web/Models/Deal/UpdateSellDealViewModel.cs
namespace OID.Web.Models.Deal
{
    public class UpdateSellDealViewModel
    {
        public int DealId { get; set; }

        public SellDealModifyViewModel SellDealModel { get; set; }
    }
}

src/OID.Web/Models/Deal/ViewDealModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using OID.DataProvider.Models.Deal;

namespace OID.Web.Models.Deal
{
    public class ViewDealModel
    {
        [Display(Name = "Номер сделки")]
        public int DealId { get; set; }

        [Display(Name = "Оператор доставки")]
        public string DeliveryTypeName { get; set; }

        [Display(Name = "Размер указанный, см")]
        public Size Size { get; set; }

        [Display(Name = "Вес для расчета стоимости доставки, грамм")]
        public int Weight { get; set; }

        [Display(Name = "Цена")]
        public double Price { get; set; }

        [Display(Name = "Комментарий")]
        public string Comment { get; set; }

        [Display(Name = "Продавец")]
        public string SellerName { get; set; }

        [Display(Name = "Покупатель")]
        public string BuyerName { get; set; }

        [Display(Name = "Объекты сделки")]
        public IList<DealObject> DealObjects { get; set; }

        public bool AcceptedByMe { get; set; }

        public bool AcceptedByPartner { get; set; }

        public bool IsBlocked { get; set; }

        public bool IsAccepted { get; set; }

        public DealType DealType { get; set; }

        public class DealObject
        {
            public int ObjectId { get; set; }

            public int CheckListId { get; set; }

            public string ObjectName { get; set; }

            public IList<ObjectCheck> ObjectChecks { get; set; }

            public int DealObjectId { get; set; }

            [Display(Name = "Подтверждено партнером")]
            public bool AcceptedByMe { get; set; }

            [Display(Name = "Подтверждено мной")]
            public bool AcceptedByPartner { get; set; }

            public class ObjectCheck
            {
                [Display(Name = "Подробное описание проверки")]
                public string Description { get; set; }

                [Display(Name = "Фотография для проверки")]
                public string ImageUrl { get; set; }
            }
        }
    }
}

src/OID.Web/Controllers/ObjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OID.Core;
using OID.DataProvider.Interfaces;
using OID.DataProvider.Models;
using OID.DataProvider.Models.Object;
using OID.DataProvider.Models.Object.In;
using OID.Web.Authenticate;
using OID.Web.Models;
using OID.Web.Models.Object;

namespace OID.Web.Controllers
{
    [Authorize("HasSessionID")]
    public class ObjectController : OIDController
    {
        private readonly IDealObjectProvider _dealObjectProvider;
        private readonly IMapper _mapper;

        public ObjectController(IDealObjectProvider dealObjectProvider, IMapper mapper)
        {
            _dealObjectProvider = dealObjectProvider;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var objects = await _dealObjectProvider.GetUserObjects();
            if (objects.ResultMessage.MessageType != MessageType.Error)
            {
                var model = _mapper.Map<List<ObjectListViewModel>>(objects.Model);
                return View(model);
            }
            else
            {
                ShowError(objects.ResultMessage.Message);
            }

            return RedirectToIndex();
        }

        public async Task<IActionResult> Create()
        {
            var model = new ObjectModifyViewModel();

            var categories = await _dealObjectProvider.GetCategories();

            model.CategoryList = new SelectList(categories.Model, nameof(ObjectCategory.Id), nameof(ObjectCategory.Name));
            model.ObjectStatusType = ObjectStatusType.WantSell;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ObjectModifyViewModel model)
        {
            if (ModelState.IsValid)
            {
                var checks = model.ObjectChecks.Select(c => new DealCheck(((int) c.CheckType).ToString(), c.Description));
                var createObjectModel = new CreateDealObject(model.CategoryCode, ((int) model.ObjectStatusType).ToString(), model.Name, model.Description, checks);
                var createObjectResult = await _dealObjectProvider.CreateObject(createObjectModel);

                if (createObjectResult.ResultMessage.MessageType != MessageType.Error)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ShowError(createObjectResult.ResultMessage.Message);

                }
            }

            return View(model);
        }

        public async Task<IActionResult> Update(string objectID, string checkListId)
        {
            var categoriesTask = _dealObjectProvider.GetCategories();
            var checksTask = _dealObjectProvider.GetChecks(checkListId);
            var userObjectTask = _dealObjectProvider.GetUserObject(objectID);

            await Task.WhenAll(categoriesTask, checksTask, userObjectTask);

            var userObject = userObjectTask.Result.Model;

            var modifyModel = new ObjectModifyViewModel
            {
                CategoryList = new SelectList(categoriesTask.Result.Model, nameof(ObjectCategory.Id), nameof(ObjectCategory.Name)),
                ObjectChecks = _mapper.Map<IList<ObjectModifyViewModel.ObjectCheck>>(checksTask.Result.Model),
                Name = userObject.Name,
                ObjectStatusType = (ObjectStatusType) Int32.Parse(userObject.StatusId),
                Description = userObject.Description,
                CategoryCode = userObject.CategoryId
            };

            var model = new UpdateObjectViewModel
            {
                ModifyViewModel = modifyModel,
                ObjectId = objectID,
                CheckListId = checkListId
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(string objectID, string checkListId, ObjectModifyViewModel model)
        {
            if (ModelState.IsValid)
            {
                var checks = model
                    .ObjectChecks
                    .Select(c => new DealCheck(((int) c.CheckType).ToString(), c.Description,c.CheckId))
                    .ToList();

                var checksToAdd = checks
                    .Where(c => String.IsNullOrEmpty(c.CheckId))
                    .ToList();
                var addChecksTask = _dealObjectProvider.CreateChecks(checksToAdd, checkListId, objectID);

                var checksIds = checks
                    .Where(c => !String.IsNullOrEmpty(c.CheckId)).Select(c => c.CheckId);

                var oldChecks = await _dealObjectProvider.GetChecks(checkListId);
                var oldChecksIds = oldChecks.Model.Select(c => c.CheckId);

                var checksToDelete = oldChecksIds.Where(c => !checksIds.Contains(c.ToString()))
                    .Select(c => c.ToString())
                    .ToList();
                var deleteChecksTask = _dealObjectProvider.DeleteChecks(checksToDelete, checkListId, objectID);

                var updateObjectModel = new UpdateDealObject(objectID, model.CategoryCode, ((int) model.ObjectStatusType).ToString(), model.Name, model.Description);
                var updateObjectTask = _dealObjectProvider.UpdateObject(updateObjectModel);

                await Task.WhenAll(addChecksTask, deleteChecksTask, updateObjectTask);

                if (addChecksTask.Result.ResultMessage.MessageType != MessageType.Error
                    && deleteChecksTask.Result.ResultMessage.MessageType != MessageType.Error
                    && updateObjectTask.Result.ResultMessage.MessageType != MessageType.Error)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ShowError(updateObjectTask.Result.ResultMessage.Message);

                }
            }

            var categories = await _dealObjectProvider.GetCategories();
            model.CategoryList = new SelectList(categories.Model, nameof(ObjectCategory.Id), nameof(ObjectCategory.Name));

            return View(new UpdateObjectViewModel
            {
                CheckListId = checkListId,
                ModifyViewModel = model,
                ObjectId = objectID
            });
        }

        public async Task<IActionResult> Copy(string objectID, string checkListId)
        {
            var categoriesTask = _dealObjectProvider.GetCategories();
            var checksTask = _dealObjectProvider.GetChecks(checkListId);
            var userObjectTask = _dealObjectProvider.GetUserObject(objectID);

            await Task.WhenAll(categoriesTask, checksTask, userObjectTask);

            var userObject = userObjectTask.Result.Model;

            var model = new ObjectModifyViewModel
            {
                CategoryList = new SelectList(categoriesTask.Result.Model, nameof(ObjectCategory.Id), nameof(ObjectCategory.Name)),
                ObjectChecks = _mapper.Map<IList<ObjectModifyViewModel.ObjectCheck>>(checksTask.Result.Model),
                Name = userObject.Name,
                ObjectStatusType = (ObjectStatusType) Int32.Parse(userObject.StatusId),
                Description = userObject.Description,
                CategoryCode = userObject.CategoryId
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Copy(ObjectModifyViewModel model)
        {
            if (ModelState.IsValid)
            {
                var checks = model.ObjectChecks.Select(c => new DealCheck(((int) c.CheckType).ToString(), c.Description));
                var createObjectModel = new CreateDealObject(model.CategoryCode, ((int) model.ObjectStatusType).ToString(), model.Name, model.Description, checks);
                var createObjectResult = await _dealObjectProvider.CreateObject(createObjectModel);

                if (createObjectResult.ResultMessage.MessageType != MessageType.Error)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ShowError(createObjectResult.ResultMessage.Message);

                }
            }

            var categories = await _dealObjectProvider.GetCategories();
            model.CategoryList = new SelectList(categories.Model, nameof(ObjectCategory.Id), nameof(ObjectCategory.Name));

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string objectId)
        {
            var deleteResult = await _dealObjectProvider.DeleteObject(objectId);
            if (deleteResult.ResultMessage.MessageType == MessageType.Information)
            {
                ShowSuccess("Успешно удален!");
                
            }
            else
            {
                ShowError("При обновление произошла ошибка!");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

src/OID.Web/Views/Deal/CreateBuy.cshtml
@model OID.Web.Models.Deal.DealModifyModel

<form method="post">
    @Html.Partial("Partials/BuyDealPartial", Model)
    <button type="submit" class="btn-success btn">Создать</button>
</form>

src/OID.Web/Views/Deal/CreateSell.cshtml
@model OID.Web.Models.Deal.SellDealModifyViewModel

<form method="post" asp-action="CreateSell">
    @Html.Partial("Partials/SellDealPartial", Model)
    <button type="submit" class="btn-success btn">Создать</button>
</form>

src/OID.Web/Views/Deal/Index.cshtml
@using System.Threading.Tasks
@using OID.DataProvider.Models.Deal

@model List<OID.Web.Models.Deal.ItemDealViewModel>

<div>
    <div class="btn-group" role="group" style="margin-bottom: 15px">
        <a href="@Url.Action("CreateBuy")" class="btn btn-lg btn-info">Хочу купить</a>
        <a href="@Url.Action("CreateSell")" class="btn btn-lg btn-info">Хочу продать</a>
        <a href="@Url.Action("CreateSell")" class="btn btn-lg btn-info">Принять сделку</a>
    </div>
    <div>
        <table class="table table-hover" id="dealList">
            <thead>
                <tr class="active">
                    <th>Объекты</th>
                    <th>Цена</th>
                    <th>Комментарий</th>
                    <th>Номер сделки</th>
                    <th>Пин</th>
                    <th>Тип сделки</th>
                    <th>Дата создания</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var deal in Model)
                {
                    <tr data-deal-id="@deal.DealId">
                        <td>
                            @deal.Objects
                        </td>
                        <td>
                            @deal.Price
                        </td>
                        <td>
                            @deal.Comment
                        </td>
                        <td>
                            @deal.DealId
                        </td>
                        <td>
                            @deal.Pin
                        </td>
                        <td>
                            @(deal.DealType == DealType.Buy ? "Покупка" : "Продажа")
                        </td>
                        <td>
                            @deal.CreateDate
                        </td>
                        <td>
                            @if (deal.DealType == DealType.Sell)
                            {
                                <a href="@Url.Action("UpdateSell", new {dealId = deal.DealId})" class="btn btn-warning">Редактировать</a>
                            }
                            else if (deal.DealType == DealType.Buy)
                            {
                                <a href="@Url.Action("UpdateBuy", new {dealId = deal.DealId})" class="btn btn-warning">Редактировать</a>
                            }

                            <form asp-action="Delete" id="deleteObject@(deal.DealId)" style="display: inline">
                                <input type="hidden" name="objectId" value="@deal.DealId" />
                                <button class="btn btn-danger" type="button" onclick="deleteObject('#deleteObject@(deal.DealId)')"><span class="glyphicon glyphicon-trash"></span></button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>

            @Html.Partial("_ConfirmAlert")
        </table>
    </div>
</div>

src/OID.Web/Views/Deal/UpdateBuy.cshtml
@model OID.Web.Models.Deal.UpdateBuyDealViewModel

<form method="post">
    <input type="hidden" asp-for="DealId" />
    @Html.Partial("Partials/BuyDealPartial", Model.DealModel)
    <button type="submit" class="btn-success btn">Сохранить</button>
</form>

src/OID.Web/Views/Deal/UpdateSell.cshtml
@using System.Threading.Tasks
@model OID.Web.Models.Deal.UpdateSellDealViewModel

<form method="post" asp-action="UpdateSell">
    <input type="hidden" asp-for="DealId"/>
    @Html.Partial("Partials/SellDealPartial", Model.SellDealModel)
    <button type="submit" class="btn-success btn">Сохранить</button>
</form>

src/OID.Web/Views/Deal/ViewDeal.cshtml
@using System.Threading.Tasks
@using OID.DataProvider.Models.Deal
@using OID.Web.Models.Deal
@model OID.Web.Models.Deal.ViewDealModel

@if (!Model.IsAccepted)
{
    <div class="alert alert-warning info-block-many" role="alert">Сделка еще не принята партнером</div>
}

@if (Model.AcceptedByPartner)
{
    <div class="alert alert-success info-block-many" role="alert">Подтверждено партнером</div>
}
else if (Model.IsAccepted)
{
    <div class="alert alert-warning info-block-many" role="alert">Ожидается подтверждение от партнера</div>
}

@if (Model.AcceptedByMe)
{
    <div class="alert alert-success info-block-many" role="alert">Подтверждено мной</div>
}


<div class="row" style="margin-top: 20px;">
    <div class="col-md-3">
        <div class="form-group">
            <label asp-for="DealId"></label>
            <input asp-for="DealId" disabled="disabled" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Price"></label>
            <input asp-for="Price" disabled="disabled" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Comment"></label>
            <textarea asp-for="Comment" disabled="disabled" class="form-control"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="SellerName"></label>
            <input asp-for="SellerName" disabled="disabled" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="BuyerName"></label>
            <input asp-for="BuyerName" disabled="disabled" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="DeliveryTypeName"></label>
            <input asp-for="DeliveryTypeName" disabled="disabled" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Weight"></label>
            <input asp-for="Weight" disabled="disabled" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Size" style="display: block"></label>
            <input asp-for="Size.Height" style="display: inline; width: 65px;" disabled="disabled" class="form-control" />
            <input asp-for="Size.Width" style="display: inline;width: 65px;" disabled="disabled" class="form-control" />
            <input asp-for="Size.Length" style="display: inline;width: 65px;" disabled="disabled" class="form-control" />
        </div>
        <div>
            @if (!Model.IsBlocked || (Model.DealObjects.All(o => o.AcceptedByMe && o.AcceptedByPartner) && !Model.AcceptedByMe))
            {

                <div class="form-group">
                    @if (!Model.IsBlocked)
                    {
                        <a asp-action="@(Model.DealType == DealType.Buy ? "UpdateBuy" : "UpdateSell")" class="btn btn-info" asp-route-dealId="@Model.DealId">Редактировать</a>
                    }

                    @if (Model.DealObjects.All(o => o.AcceptedByMe && o.AcceptedByPartner) && !Model.AcceptedByMe)
                    {
                        <form asp-action="ApproveDeal" asp-route-dealId="@Model.DealId" asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString" style="display: inline">
                            <button class="btn btn-success" type="submit">Подтвердить</button>
                        </form>
                    }
                </div>
            }
        </div>
    </div>
    <div class="col-md-9">
        @foreach (var dealObject in Model.DealObjects)
        {
            <div class="panel panel-info">
                <div class="panel-heading"> <a asp-controller="Object" asp-action="Update" asp-route-objectID="@dealObject.ObjectId" asp-route-checkListId="@dealObject.CheckListId">@dealObject.ObjectName</a></div>

                <div class="panel-body">
                    @foreach (var objectCheck in dealObject.ObjectChecks)
                    {
                        <div class="deal_check">
                            <div>
                                <p>@objectCheck.Description</p>
                                <img src="@objectCheck.ImageUrl" />
                            </div>
                        </div>
                    }

                    @if (dealObject.AcceptedByPartner)
                    {
                        <span class="label  label-success">Подтверждено партнером</span>
                    }
                    else
                    {
                        <span class="label  label-warning ">Ожидается подтверждение от партнера</span>
                    }

                    @if (dealObject.AcceptedByMe)
                    {
                        <span class="label  label-success">Подтверждено мной</span>
                    }
                    else
                    {
                        <form asp-action="ApproveObject" asp-route-dealObjectId="@dealObject.DealObjectId" asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString">
                            <button class="btn btn-success btn-sm" type="submit" style="display: block">Подтвердить</button>
                        </form>

                    }
                </div>
            </div>
        }
    </div>
</div>